name: shared_preferences

version: 0.2.2
description: A Flutter plugin for reading and writing simple key-value pairs.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/shared_preferences

flutter:
  plugin:
    androidPackage: io.flutter.plugins.shared_preferences
    pluginClass: SharedPreferencesPlugin

dependencies:
  flutter:
    sdk: flutter

environment:
    sdk: ">=1.8.0 <2.0.0"
