name: google_sign_in
description: Google Sign-In plugin for Flutter.

flutter:
  plugin:
    androidPackage: io.flutter.plugins.googlesignin
    pluginClass: GoogleSignInPlugin

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.4

dev_dependencies:
  mockito: ^2.0.2
  test: ^0.12.20
