name: connectivity
description: A new flutter plugin project.
version: 0.0.1
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/connectivity

flutter:
  plugin:
    androidPackage: io.flutter.plugins.connectivity
    pluginClass: ConnectivityPlugin

dependencies:
  flutter:
    sdk: flutter
