name: url_launcher

version: 0.1.1
description: Flutter plugin for launching a URL
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/url-launcher

flutter:
  plugin:
    androidPackage: io.flutter.plugins.url_launcher
    pluginClass: UrlLauncherPlugin

dependencies:
  flutter:
    sdk: flutter
