name: url_launcher

version: 0.4.0
description: A Flutter plugin for launching a URL
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins

flutter:
  plugin:
    androidPackage: io.flutter.plugins.url_launcher
    pluginClass: UrlLauncherPlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test:
